apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: ghcr-secret # Use the secret for authentication
      containers:
        - name: nginx
          image: ghcr.io/florinelfrancisc/nginx-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
