---
- name: Rolling Update for Kubernetes Deployment
  hosts: localhost
  tasks:
    - name: Get current deployment details
      command: kubectl get deployment nginx-app -o=jsonpath='{.spec.template.spec.containers[0].image}'
      register: current_image
      changed_when: false

    - name: Update Kubernetes Deployment to the latest image
      command: kubectl set image deployment/nginx-app nginx=ghcr.io/florinelfrancisc/nginx-app:latest
      register: update_result
      failed_when: update_result.rc != 0

    - name: Wait for Deployment rollout to finish
      command: kubectl rollout status deployment/nginx-app
      register: rollout_status
      failed_when: rollout_status.rc != 0

    - name: Validate if the new version is running
      command: kubectl get deployment nginx-app -o=jsonpath='{.spec.template.spec.containers[0].image}'
      register: new_image
      changed_when: false

    - name: Rollback if update failed
      command: kubectl rollout undo deployment/nginx-app
      when: new_image.stdout != "ghcr.io/florinelfrancisc/nginx-app:latest"

    - name: Get current deployment details
      command: kubectl get deployment nginx-app -o=jsonpath='{.spec.template.spec.containers[0].image}'
      register: current_image
      changed_when: false

    - name: Update Kubernetes Deployment only if a new image is available
      command: kubectl set image deployment/nginx-app nginx=ghcr.io/florinelfrancisc/nginx-app:latest
      when: current_image.stdout != "ghcr.io/florinelfrancisc/nginx-app:latest"
