name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*" # Runs when a tag like v1.0.0 is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Tag Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/florinelfrancisc/nginx-app:${{ env.VERSION }} .
          docker build -t ghcr.io/florinelfrancisc/nginx-app:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/florinelfrancisc/nginx-app:${{ env.VERSION }}
          docker push ghcr.io/florinelfrancisc/nginx-app:latest
